#docker build --tag ipsjdasadc/adc:20200908 --file Dockerfile-patch20200908 --no-cache .

#FROM	ipsjdasadc/adc:20200902
FROM	ipsjdasadc/adc:20200827

USER	adc
RUN	cd /home/adc/adc2019/ && \
	git pull

USER	root
