FROM	ipsjdasadc/adc:latest

RUN	yum install -y \
	    epel-release \
	    gcc-c++ \
	    make

USER	adc
RUN	conda activate adc2019dev && \
	cd /home/adc/adc2019/client-app/ && \
	npm install

USER	root
